Repository openshift/route-monitor-operator, pull requests merged in 2020-09, with the labels that each got.

#2 fix: make build pass
  PROJECT
  controllers/routemonitor_controller.go
  controllers/suite_test.go
  go.mod
  main.go
Labels: lgtm

#3 fix(sample): correct sample
  config/crd/bases/monitoring.openshift.io_routemonitors.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/role.yaml
  config/samples/monitoring_v1alpha1_routemonitor.yaml
  controllers/suite_test.go
Labels: approved, lgtm, tide/merge-method-squash

#4 rogreen/make routemonitor create servicemonitor
  api/v1alpha1/routemonitor_types.go
  config/default/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/routemonitor_controller.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm

#5 feat(routemonitor): routemonitor populate
  api/v1alpha1/routemonitor_types.go
  api/v1alpha1/routemonitor_types_supplement.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/certmanager/certificate.yaml
  config/crd/bases/monitoring.openshift.io_routemonitors.yaml
  config/crd/patches/webhook_in_routemonitors.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/samples/monitoring_v1alpha1_routemonitor.yaml
  config/webhook/service.yaml
  controllers/routemonitor_controller.go
  controllers/routemonitor_controller_supplement.go
  main.go
Labels: approved, lgtm, tide/merge-method-squash

#6 owners: add georgettica to approvers
  OWNERS
Labels: approved, lgtm

#7 feat(routemonitor): make code work with tests
  .gitignore
  Dockerfile
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/routemonitor_types.go
  api/v1alpha1/routemonitor_types_supplement.go
  config/crd/bases/monitoring.openshift.io_routemonitors.yaml
  config/manager/kustomization.yaml
  config/rbac/role.yaml
  controllers/routemonitor/routemonitor_controller.go
  controllers/routemonitor/routemonitor_controller_supplement.go
  controllers/routemonitor/routemonitor_controller_supplement_suite_test.go
  controllers/routemonitor/routemonitor_controller_supplement_test.go
  controllers/routemonitor_controller.go
  controllers/routemonitor_controller_supplement.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
  pkg/util/errors/errors.go
  pkg/util/reconcile/reconcile_operations.go
  pkg/util/tests/generated/mocks/cr-client.go
  pkg/util/tests/generated/mocks/status-writer.go
  pkg/util/tests/mockgenerator/client/client.go
Labels: approved, lgtm
