Repository openshift/route-monitor-operator, pull requests merged in 2020-11, with the labels that each got.

#14 Add ClusterUrlMontitor
  Makefile
  PROJECT
  api/v1alpha1/clusterurlmonitor_types.go
  api/v1alpha1/routemonitor_types.go
  api/v1alpha1/routemonitor_types_supplement.go
  api/v1alpha1/v1alpha1_suite_test.go
  api/v1alpha1/v1alpha1_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/monitoring.openshift.io_clusterurlmonitors.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_clusterurlmonitors.yaml
  config/crd/patches/webhook_in_clusterurlmonitors.yaml
  config/rbac/clusterurlmonitor_editor_role.yaml
  config/rbac/clusterurlmonitor_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/monitoring_v1alpha1_clusterurlmonitor.yaml
  controllers/clusterurlmonitor/clusterurlmonitor.go
  controllers/clusterurlmonitor/clusterurlmonitor_suite_test.go
  controllers/clusterurlmonitor/clusterurlmonitor_supplement.go
  controllers/clusterurlmonitor/clusterurlmonitor_test.go
  controllers/dummy_controller.go
  controllers/routemonitor/adder/adder.go
  controllers/routemonitor/adder/adder_test.go
  controllers/routemonitor/deleter/deleter.go
  controllers/routemonitor/deleter/deleter_test.go
  controllers/routemonitor/routemonitor.go
  controllers/routemonitor/routemonitor_interface.go
  controllers/routemonitor/routemonitor_supplement.go
  controllers/routemonitor/routemonitor_test.go
  controllers/routemonitor/supplement/supplement.go
  controllers/routemonitor/supplement/supplement_test.go
  go.mod
  go.sum
  main.go
  pkg/blackboxexporter/blackboxexporter.go
  pkg/blackboxexporter/blackboxexporter_suite_test.go
  pkg/blackboxexporter/blackboxexporter_test.go
  pkg/consts/blackbox/blackbox.go
  pkg/consts/finalizer.go
  pkg/consts/test/error/error.go
  pkg/consts/test/init/init.go
  pkg/util/finalizer/finalizer.go
  pkg/util/finalizer/finalizer_test.go
  pkg/util/templates/templates.go
  pkg/util/test/generated/mocks/routemonitor/blackboxexporter.go
  pkg/util/test/generated/mocks/routemonitor/routemonitor.go
  pkg/util/test/helper/helper.go
Labels: approved, lgtm, ok-to-test, size/XXL

#17 Add readme section for ClusterUrlMonitors
  README.md
Labels: approved, lgtm

#18 owners: add vrutkovs to reviewers
  OWNERS
Labels: approved, lgtm, size/XS
