Repository openshift/route-monitor-operator, pull requests merged in 2020-12, with the labels that each got.

#16 Add integration test suite and base tooling
  Makefile
  README.md
  config/manager/kustomization.yaml
  config/rbac/role.yaml
  controllers/routemonitor/routemonitor.go
  go.sum
  hack/test-integration-setup.sh
  int/int_suite_test.go
  int/int_test.go
  int/integration.go
Labels: approved, lgtm, ok-to-test, size/L, tide/merge-method-squash

#21 feat(project): make repo v3 complient
  PROJECT
Labels: approved, lgtm

#20 feat(blackbox): change image location
  config/manager/manager.yaml
  controllers/clusterurlmonitor/clusterurlmonitor.go
  controllers/routemonitor/routemonitor.go
  main.go
  pkg/blackboxexporter/blackboxexporter.go
Labels: approved, lgtm

#23 georgettica/app interface old way
  .gitignore
  Makefile
  bundle.Dockerfile
  config/manifests/bases/route-monitor-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  config/scorecard/bases/config.yaml
  config/scorecard/kustomization.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
  hack/app_sre_build_deploy.sh
  hack/app_sre_create_image_catalog.sh
  hack/generate-operator-bundle.py
Labels: approved, lgtm

#24 fix prometheus-operator dependency
  controllers/routemonitor/routemonitor.go
  go.mod
  go.sum
Labels: approved, lgtm

#25 fix(gomod): update deps
  go.mod
  go.sum
Labels: approved, lgtm

#26 fix(makefile): [HACK] seperate go-generate
  Makefile
Labels: approved, lgtm

#28 feat(hack): containerize operator-sdk commands
  Makefile
  hack/app_sre_build_deploy.sh
  hack/app_sre_create_image_catalog.sh
Labels: approved, lgtm

#29 feat(hack): change python and add kustomize
  Makefile
  hack/generate-operator-bundle.py
Labels: approved, lgtm

#30 feat(hack): make command use correct creds
  Makefile
  hack/app_sre_build_deploy.sh
  hack/app_sre_create_image_catalog.sh
Labels: approved, lgtm, tide/merge-method-squash

#32 partial Revert "feat(hack): make command use correct creds"
  Makefile
  hack/app_sre_create_image_catalog.sh
  hack/pipeline.dockerfile
Labels: approved, lgtm, tide/merge-method-squash

#34 feat(makefile): make kustomize configurable
  Makefile
Labels: approved, lgtm

#35 fix(hack): change root permissions
  hack/app_sre_create_image_catalog.sh
Labels: approved, lgtm

#36 georgettica/add syncset template
  .gitignore
  Makefile
  config/olm/catalogsource.yaml
  config/olm/kustomization.yaml
  config/olm/operatorgroup.yaml
  config/olm/subscription.yaml
  config/rbac/kustomization.yaml
  hack/generate_template.py
  hack/olm-registry/olm-artifacts-template.yaml
  hack/templates/package.yaml
  hack/templates/selectorsyncset.yaml
  hack/templates/template.yaml
Labels: approved, lgtm, tide/merge-method-squash

#38 fix(makefile): fix unwanted delete
  Makefile
  hack/app_sre_build_deploy.sh
Labels: approved, lgtm

#37 feat(hack): root perm fixing
  hack/app_sre_create_image_catalog.sh
Labels: approved, lgtm

#39 Update app_sre_build_deploy.sh
  hack/app_sre_build_deploy.sh
Labels: approved, lgtm

#42 hack: dockerize build pipeline more and fix permission issue on slave
  .gitignore
  hack/app_sre_create_image_catalog.sh
  hack/bundler.sh
  hack/pipeline.dockerfile
Labels: approved, lgtm

#43 hack: remove leftover of base_command
  hack/app_sre_create_image_catalog.sh
Labels: approved

#44 hack,olm: remove operatorgroup
  config/olm/kustomization.yaml
  config/olm/operatorgroup.yaml
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm
