Repository openshift/route-monitor-operator, pull requests merged in 2021-02, with the labels that each got.

#79 [OSD-6345] fix: Make changes to OLM template permanent
  config/olm/operatorgroup.yaml
Labels: approved, lgtm

#78 OSD-6298 - blackbox namespace modular
  config/manager/manager.yaml
  controllers/clusterurlmonitor/clusterurlmonitor.go
  main.go
  pkg/blackboxexporter/blackboxexporter.go
  pkg/consts/blackbox/blackbox.go
Labels: approved, lgtm

#76 Autorun `make generate-syncsets` via GitHub actions
  .github/workflows/makecommit.yml
  CONTRIBUTING.md
  hack/generate-syncset.sh
Labels: approved, kind/feature, lgtm

#80 feat(blackbox): make blackbox prefer infra nodes [OSD-6337]
  pkg/blackboxexporter/blackboxexporter.go
Labels: approved, lgtm

#60 [OSD-6057]: add SLO API
  api/v1alpha1/common_types.go
  api/v1alpha1/routemonitor_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/monitoring.openshift.io_routemonitors.yaml
  config/rbac/role.yaml
  config/samples/monitoring_v1alpha1_routemonitor.yaml
  controllers/routemonitor/adder/adder.go
  controllers/routemonitor/adder/adder_test.go
  controllers/routemonitor/deleter/deleter.go
  controllers/routemonitor/deleter/deleter_test.go
  controllers/routemonitor/routemonitor.go
  controllers/routemonitor/routemonitor_interface.go
  controllers/routemonitor/routemonitor_supplement.go
  controllers/routemonitor/routemonitor_test.go
  go.mod
  hack/test-integration.sh
  int/int_test.go
  int/integration.go
  pkg/util/errors/errors.go
  pkg/util/templates/templates.go
  pkg/util/test/generated/mocks/routemonitor/routemonitor.go
Labels: approved, lgtm, tide/merge-method-squash

#83 Change installMode to single/own namespace
  config/manifests/bases/route-monitor-operator.clusterserviceversion.yaml
  config/olm/operatorgroup.yaml
  hack/generate-syncset.sh
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm

#84 Change builder image
  Dockerfile
Labels: approved, lgtm

#86 support different types of operator groups
  config/manifests/bases/route-monitor-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#87 Revert OperatorGroup changes
  config/manifests/bases/route-monitor-operator.clusterserviceversion.yaml
  config/olm/operatorgroup.yaml
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm

#88 fix README markdown
  README.md
Labels: approved, lgtm

#85 :memo:(testing): add tests documentation
  CONTRIBUTING.md
  TESTS.md
  pkg/util/test/helper/helper.go
Labels: approved, lgtm

#89 Fix README markdown
  README.md
Labels: approved, lgtm

#90 fix(servicemonitor): make servicemonitor work [OSD-6541]
  controllers/clusterurlmonitor/clusterurlmonitor.go
  controllers/clusterurlmonitor/clusterurlmonitor_supplement.go
  controllers/clusterurlmonitor/clusterurlmonitor_test.go
  controllers/routemonitor/adder/adder.go
  controllers/routemonitor/adder/adder_test.go
  controllers/routemonitor/routemonitor.go
  controllers/routemonitor/routemonitor_supplement.go
  controllers/routemonitor/routemonitor_test.go
  hack/app_sre_build_deploy.sh
  hack/generate-syncset.sh
  main.go
  pkg/blackboxexporter/blackboxexporter.go
  pkg/blackboxexporter/blackboxexporter_test.go
  pkg/consts/blackboxexporter/blackboxexporter.go
  pkg/util/templates/templates.go
  pkg/util/test/generated/mocks/routemonitor/blackboxexporter.go
Labels: approved, lgtm
